### ISSUE TITLE
Stylistic changes to the repo

### ISSUE THREAD

**Issue by frederikja163** [ECDAR-AAU-SW-P5/Reveaal#1]
### Protobuf installation steps missing:
**Arch:** `yay protobuf-c`
**Windows:**
Download for the windows protocol buffers should be available here: https://github.com/protocolbuffers/protobuf/releases/tag/v24.3
Afterwards add the bin folder with the precompiled protoc to your system's enviroment variabels in path, it should compile now after restarting the terminal

## Comments
There are comments in the top of both `src/DataReader/parse_edge.rs` and `src/DataReader/parse_queries.rs` that should be only two '/' instead of three. Otherwise you get information about the entire file on a single function in said file.

There are a few functions inside `src/DataReader/json_reader.rs` that document functions but only has two '/' so the comments dont show up in intellisense.

`src/ModelObjects/state.rs` first comment contains typos, should be 
```rs
/// State is a struct used for initial verification of consistency, and determinism as a state that also hols a dbm
/// This is done as the type used in refinement state pair assumes two sides of an operation
/// this should probably be refactored as it causes unnecessary confusion
```

## Warnings
remove #![allow(non_snake_case)] from [main.rs](https://github.com/ECDAR-AAU-SW-P5/Reveaal/blob/4b41c9daf115183ac615227e3589d00bd99f07f0/src/main.rs#L1) and [lib.rs](https://github.com/ECDAR-AAU-SW-P5/Reveaal/blob/4b41c9daf115183ac615227e3589d00bd99f07f0/src/lib.rs#L1)

## Rename
`src/EdgeEval/constraint_applyer.rs` -> `src/EdgeEval/constraint_applier.rs`

## Up for discussion
Move `src/DataTypes/statepair_list.rs` into `src/ModelObjects/statepair_list.rs`
Move `src/Simulation/decision.rs` into `src/ModelObjects/decision.rs`
Move `src/Simulation/graph_layout` somewhere else. Maybe protobuf?

**Comment by AleksanderRDL** [comment]
Windows protocol buffers:
I skal have downloadet windows versionen af protobuffers her: https://github.com/protocolbuffers/protobuf/releases/tag/v24.3
Efter skal i bare tilføje bin folderen til jeres enviroment variabels i Path, så burde det compile

**Comment by Aavild** [comment]
remove #![allow(non_snake_case)] from [main.rs](https://github.com/ECDAR-AAU-SW-P5/Reveaal/blob/4b41c9daf115183ac615227e3589d00bd99f07f0/src/main.rs#L1) and [lib.rs](https://github.com/ECDAR-AAU-SW-P5/Reveaal/blob/4b41c9daf115183ac615227e3589d00bd99f07f0/src/lib.rs#L1)

**Comment by Aavild** [comment]
`cargo clippy --all-targets --all-features -- -D warnings` and `cargo fmt --all -- --check` is used in the Github Validation action. Thus it makes sense for the readme to include how to run [Clippy](https://github.com/rust-lang/rust-clippy#usage)  and also [rustfmt in IDE](https://github.com/rust-lang/rustfmt#running-rustfmt-from-your-editor)
